[DevOps] Snyk Integration
h2oai/dai-deployment-templates pull request #325
Opened 2023-02-15 13:43 UTC by ChathurindaRanasinghe

**FIXED PROBLEMS**

- Fixed deprecation issues with the `set-output` command. - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- Changed the organisation to [DRIVERLESS-AI](https://app.snyk.io/org/driverless-ai).
- Invoked using new service account in Snyk (DRIVERLESS_AI_SNYK_TOKEN](https://app.snyk.io/org/driverless-ai/manage/service-accounts)) & updated the previous SNYK_TOKEN in GItHub.
- Updated GitHub Action versions for Java.
- Updated the [changed-files](https://github.com/marketplace/actions/changed-files) GitHub Action version.
- `remote-repo-url` will follow `repo/branch` format & `project-name` will follow `PRODUCT/repo/branch/file` format.

**PARENT ISSUES**

- https://github.com/h2oai/h2o-ops/issues/266
- https://github.com/h2oai/h2o-ops/issues/241

2023-02-16 10:12 UTC, hasithjp requested changes

2023-02-16 10:12 UTC, hasithjp commented on .github/workflows/snyk-scan.yml
>                aws-lambda-scorer/terraform-recipe/build.gradle
please use regex

2023-02-16 10:12 UTC, hasithjp commented on .github/workflows/snyk-scan.yml
>            fetch-depth: 2
please change tag regex as in other PRs

2023-02-16 13:54 UTC, ChathurindaRanasinghe commented on .github/workflows/snyk-scan.yml
>                aws-lambda-scorer/terraform-recipe/build.gradle
done

2023-02-16 13:54 UTC, ChathurindaRanasinghe commented on .github/workflows/snyk-scan.yml
>            fetch-depth: 2
sure

2023-02-16 14:04 UTC, hasithjp approved these changes

2023-02-21 05:48 UTC, hasithjp approved these changes

2023-02-21 05:50 UTC, merged